spring:
  application:
    name: payment

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

queries:
  update-payment-status: "UPDATE PaymentRequest SET paymentStatus= :status WHERE paymentId = :id"